# funicular config

# Api Keys
[[API]]
    # Use API keys to get info?
    use=true
    # overwrite existing info?
    overwrite=false
    OMDB=""

# Test Lib
[[Library]]
    name="Test Dir"
    location="./test_dirs/Films/"
    folder_structure=["picture_list"]
    page_titles=["Film"]
