# funicular config


# Library Info
[[Library]]
    name="Film"
    location="/media/slam/C/Films"
    folder_structure=["picture_list","endpoint"]

[[Library]]
    name="TV"
    location="/media/slam/D/TV"
    folder_structure=["picture_list","list","list","endpoint"]

[[Library]]
    name="Stand Up"
    location="/media/slam/E/library/standup"
    folder_structure=["picture_list","list","endpoint"]
